name: Update Events

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3 AM UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-events:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd gleisgarten-scraper
          npm install
          
      - name: Run scraper
        run: |
          cd gleisgarten-scraper
          node scrape-gleisgarten.js
          
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add events.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update events" && git push)
