name: Update Events

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches:
      - test-workflow

jobs:
  update-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd gleisgarten-scraper
          npm install
          
      - name: Install Playwright
        run: |
          cd gleisgarten-scraper
          npx playwright install chromium
          sudo npx playwright install-deps chromium
          
      - name: Run scraper
        run: |
          cd gleisgarten-scraper
          node scrape-gleisgarten.js
          
      - name: Commit and push if changes
        run: |
          git config --global user.name 'Hansi7899'
          git config --global user.email 'johann7899@gmail.com'
          git add gleisgarten-scraper/events.json
          git commit -m "Auto-update events" || echo "No changes to commit"
          git push origin ${GITHUB_REF#refs/heads/}
